<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vicky" failures="19" tests="21" name="Test" time="324.643" errors="0" timestamp="2023-11-20T15:07:24 IST">
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGivingAlreadyRegisteredMobileNumberOTPTest" time="10.727">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGivingAlreadyRegisteredMobileNumberOTPTest(Done_LoginErrors_StgTest.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGivingAlreadyRegisteredMobileNumberOTPTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignOutErrors_StgTest" name="signOutByClickingOnCancelBtnErrorTest" time="12.078"/>
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationExistingEmailGivenErrorTest" time="32.064">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationExistingEmailGivenErrorTest(Done_SignUpModuleNegativeScenarios_StgTest.java:260)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationExistingEmailGivenErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGivingNotRegisteredMobileNumberErrorTest" time="9.851">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGivingNotRegisteredMobileNumberErrorTest(Done_LoginErrors_StgTest.java:159)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGivingNotRegisteredMobileNumberErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationExistingPhoneNumberGivenErrorTest" time="30.813">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationExistingPhoneNumberGivenErrorTest(Done_SignUpModuleNegativeScenarios_StgTest.java:355)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationExistingPhoneNumberGivenErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGiving1NumberAsMobileNumberErrorTest" time="9.905">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGiving1NumberAsMobileNumberErrorTest(Done_LoginErrors_StgTest.java:234)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGiving1NumberAsMobileNumberErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationPhoneNumberNotGivenErrorTest" time="18.756">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationPhoneNumberNotGivenErrorTest(Done_SignUpModuleNegativeScenarios_StgTest.java:430)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationPhoneNumberNotGivenErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGiving3NumbersAsMobileNumberErrorTest" time="9.661">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGiving3NumbersAsMobileNumberErrorTest(Done_LoginErrors_StgTest.java:308)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGiving3NumbersAsMobileNumberErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationGivenWrongReferralCodeErrorTest" time="18.562">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationGivenWrongReferralCodeErrorTest(Done_SignUpModuleNegativeScenarios_StgTest.java:520)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationGivenWrongReferralCodeErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGivingMoreThan12NumbersAsMobileNumberErrorTest" time="9.728">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGivingMoreThan12NumbersAsMobileNumberErrorTest(Done_LoginErrors_StgTest.java:382)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGivingMoreThan12NumbersAsMobileNumberErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationGivenRightReferralCodePassedTest" time="18.485">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationGivenRightReferralCodePassedTest(Done_SignUpModuleNegativeScenarios_StgTest.java:591)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationGivenRightReferralCodePassedTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGivingMoreThan14NumbersAsMobileNumberErrorTest" time="9.514">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGivingMoreThan14NumbersAsMobileNumberErrorTest(Done_LoginErrors_StgTest.java:457)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGivingMoreThan14NumbersAsMobileNumberErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationSkipNameErrorTest" time="20.551">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationSkipNameErrorTest(Done_SignUpModuleNegativeScenarios_StgTest.java:667)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationSkipNameErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGivingSpecialCharsAsMobileNumberErrorTest" time="9.82">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGivingSpecialCharsAsMobileNumberErrorTest(Done_LoginErrors_StgTest.java:532)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGivingSpecialCharsAsMobileNumberErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationSkipHeardAboutUsDropDwnValueErrorTest" time="16.014">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationSkipHeardAboutUsDropDwnValueErrorTest(Done_SignUpModuleNegativeScenarios_StgTest.java:737)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationSkipHeardAboutUsDropDwnValueErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByClickingOnLoginWithGoogleErrorTest" time="11.829">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByClickingOnLoginWithGoogleErrorTest(Done_LoginErrors_StgTest.java:685)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByClickingOnLoginWithGoogleErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationEnterMoreThan10NumbersInMobileNumTextFieldErrorTest" time="18.445">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest.whileSignIntoApplicationEnterMoreThan10NumbersInMobileNumTextFieldErrorTest(Done_SignUpModuleNegativeScenarios_StgTest.java:807)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- whileSignIntoApplicationEnterMoreThan10NumbersInMobileNumTextFieldErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGivingRegisteredMobileNumberPassTest" time="10.313">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGivingRegisteredMobileNumberPassTest(Done_LoginErrors_StgTest.java:756)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGivingRegisteredMobileNumberPassTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest" name="whileSignIntoApplicationGivenInvalidEmailErrorTest" time="27.412"/>
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGiving10NumbersAs0MobileNumberErrorTest" time="9.853">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGiving10NumbersAs0MobileNumberErrorTest(Done_LoginErrors_StgTest.java:825)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGiving10NumbersAs0MobileNumberErrorTest -->
  <testcase classname="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest" name="loginByGiving1stNumberAs0MobileNumberErrorTest" time="10.143">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_LoginErrors_StgTest.loginByGiving1stNumberAs0MobileNumberErrorTest(Done_LoginErrors_StgTest.java:897)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginByGiving1stNumberAs0MobileNumberErrorTest -->
</testsuite> <!-- Test -->
